### ISSUE TITLE
Some revisions are not converted to links to GH commits

### ISSUE THREAD

**Issue by bennylp** [ismangil/trac-hub#3]
For example:
- https://github.com/pjsip/testproject12/issues/1516

**Comment by ismangil** [comment]
Needs to look into difference of for example what's different  in Trac for #2173 and #1516

**Comment by bennylp** [comment]
One difference is the successful ones have leading "r" before the ref number

**Comment by ismangil** [comment]
@bennylp Not really,  https://github.com/pjsip/testproject12/issues/2173 both  are converted successfully

r5928
5930

**Comment by ismangil** [comment]
Problem caused by incomplete revmap file - current revmap file only from trunk. Need to generate further revmaps for all branches

**Comment by ismangil** [comment]
New revmap generated
