### ISSUE TITLE
Some ticket comments are missing

### ISSUE THREAD

**Issue by bennylp** [ismangil/trac-hub#4]
Sample:
- https://github.com/pjsip/testproject12/issues/1298

**Comment by nanangizz** [comment]
Looks okay here:
https://github.com/nanangizz/testproject1/issues/19

There are missing comments, but on purposely removed fields, i.e: milestone, version, and backported.

**Comment by bennylp** [comment]
Looks ok here too:
- https://github.com/bennylp/testpj11/issues/24
