### ISSUE TITLE
Missing early tickets

### ISSUE THREAD

**Issue by ismangil** [ismangil/trac-hub#9]
Due to GitHub usage tickets 1 to 12.

Recommend:

Importing Trac ticket 1 to 12 manual one by one - after import

**Comment by ismangil** [comment]
Ticket 1 & 4 imported, but 2 & 3 skipped

**Comment by bennylp** [comment]
Wiki in https://github.com/pjsip/pjproject/issues/2277 was not resolved and was edited manually

**Comment by ismangil** [comment]
Ticket 1-12 now imported to 2267 onwards.
